/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface PrizePoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createMatch"
      | "fund"
      | "fundedAmount"
      | "isFullyFunded"
      | "isPlayer"
      | "matches"
      | "owner"
      | "payout"
      | "refundDraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Funded"
      | "MatchCreated"
      | "MatchRefunded"
      | "Paid"
      | "PlayerRefunded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createMatch",
    values: [BytesLike, AddressLike[], BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "fund", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "fundedAmount",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isFullyFunded",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isPlayer",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "matches", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payout",
    values: [BytesLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "refundDraw",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "createMatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fund", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fundedAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isFullyFunded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isPlayer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "matches", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payout", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "refundDraw", data: BytesLike): Result;
}

export namespace FundedEvent {
  export type InputTuple = [
    matchId: BytesLike,
    funder: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [matchId: string, funder: string, amount: bigint];
  export interface OutputObject {
    matchId: string;
    funder: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchCreatedEvent {
  export type InputTuple = [
    matchId: BytesLike,
    players: AddressLike[],
    requiredStake: BigNumberish,
    rulesHash: BytesLike
  ];
  export type OutputTuple = [
    matchId: string,
    players: string[],
    requiredStake: bigint,
    rulesHash: string
  ];
  export interface OutputObject {
    matchId: string;
    players: string[];
    requiredStake: bigint;
    rulesHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchRefundedEvent {
  export type InputTuple = [matchId: BytesLike, storageHash: BytesLike];
  export type OutputTuple = [matchId: string, storageHash: string];
  export interface OutputObject {
    matchId: string;
    storageHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaidEvent {
  export type InputTuple = [
    matchId: BytesLike,
    winner: AddressLike,
    amount: BigNumberish,
    storageHash: BytesLike
  ];
  export type OutputTuple = [
    matchId: string,
    winner: string,
    amount: bigint,
    storageHash: string
  ];
  export interface OutputObject {
    matchId: string;
    winner: string;
    amount: bigint;
    storageHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlayerRefundedEvent {
  export type InputTuple = [
    matchId: BytesLike,
    player: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [matchId: string, player: string, amount: bigint];
  export interface OutputObject {
    matchId: string;
    player: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PrizePool extends BaseContract {
  connect(runner?: ContractRunner | null): PrizePool;
  waitForDeployment(): Promise<this>;

  interface: PrizePoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createMatch: TypedContractMethod<
    [
      matchId: BytesLike,
      players: AddressLike[],
      requiredStake: BigNumberish,
      rulesHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  fund: TypedContractMethod<[matchId: BytesLike], [void], "payable">;

  fundedAmount: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  isFullyFunded: TypedContractMethod<[matchId: BytesLike], [boolean], "view">;

  isPlayer: TypedContractMethod<
    [matchId: BytesLike, player: AddressLike],
    [boolean],
    "view"
  >;

  matches: TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, boolean, boolean, string, string, string] & {
        requiredStake: bigint;
        totalStake: bigint;
        paid: boolean;
        refunded: boolean;
        storageHash: string;
        winner: string;
        rulesHash: string;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  payout: TypedContractMethod<
    [matchId: BytesLike, winner: AddressLike, storageHash: BytesLike],
    [void],
    "nonpayable"
  >;

  refundDraw: TypedContractMethod<
    [matchId: BytesLike, storageHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createMatch"
  ): TypedContractMethod<
    [
      matchId: BytesLike,
      players: AddressLike[],
      requiredStake: BigNumberish,
      rulesHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fund"
  ): TypedContractMethod<[matchId: BytesLike], [void], "payable">;
  getFunction(
    nameOrSignature: "fundedAmount"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "isFullyFunded"
  ): TypedContractMethod<[matchId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isPlayer"
  ): TypedContractMethod<
    [matchId: BytesLike, player: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "matches"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, boolean, boolean, string, string, string] & {
        requiredStake: bigint;
        totalStake: bigint;
        paid: boolean;
        refunded: boolean;
        storageHash: string;
        winner: string;
        rulesHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "payout"
  ): TypedContractMethod<
    [matchId: BytesLike, winner: AddressLike, storageHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "refundDraw"
  ): TypedContractMethod<
    [matchId: BytesLike, storageHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Funded"
  ): TypedContractEvent<
    FundedEvent.InputTuple,
    FundedEvent.OutputTuple,
    FundedEvent.OutputObject
  >;
  getEvent(
    key: "MatchCreated"
  ): TypedContractEvent<
    MatchCreatedEvent.InputTuple,
    MatchCreatedEvent.OutputTuple,
    MatchCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MatchRefunded"
  ): TypedContractEvent<
    MatchRefundedEvent.InputTuple,
    MatchRefundedEvent.OutputTuple,
    MatchRefundedEvent.OutputObject
  >;
  getEvent(
    key: "Paid"
  ): TypedContractEvent<
    PaidEvent.InputTuple,
    PaidEvent.OutputTuple,
    PaidEvent.OutputObject
  >;
  getEvent(
    key: "PlayerRefunded"
  ): TypedContractEvent<
    PlayerRefundedEvent.InputTuple,
    PlayerRefundedEvent.OutputTuple,
    PlayerRefundedEvent.OutputObject
  >;

  filters: {
    "Funded(bytes32,address,uint256)": TypedContractEvent<
      FundedEvent.InputTuple,
      FundedEvent.OutputTuple,
      FundedEvent.OutputObject
    >;
    Funded: TypedContractEvent<
      FundedEvent.InputTuple,
      FundedEvent.OutputTuple,
      FundedEvent.OutputObject
    >;

    "MatchCreated(bytes32,address[],uint256,bytes32)": TypedContractEvent<
      MatchCreatedEvent.InputTuple,
      MatchCreatedEvent.OutputTuple,
      MatchCreatedEvent.OutputObject
    >;
    MatchCreated: TypedContractEvent<
      MatchCreatedEvent.InputTuple,
      MatchCreatedEvent.OutputTuple,
      MatchCreatedEvent.OutputObject
    >;

    "MatchRefunded(bytes32,bytes32)": TypedContractEvent<
      MatchRefundedEvent.InputTuple,
      MatchRefundedEvent.OutputTuple,
      MatchRefundedEvent.OutputObject
    >;
    MatchRefunded: TypedContractEvent<
      MatchRefundedEvent.InputTuple,
      MatchRefundedEvent.OutputTuple,
      MatchRefundedEvent.OutputObject
    >;

    "Paid(bytes32,address,uint256,bytes32)": TypedContractEvent<
      PaidEvent.InputTuple,
      PaidEvent.OutputTuple,
      PaidEvent.OutputObject
    >;
    Paid: TypedContractEvent<
      PaidEvent.InputTuple,
      PaidEvent.OutputTuple,
      PaidEvent.OutputObject
    >;

    "PlayerRefunded(bytes32,address,uint256)": TypedContractEvent<
      PlayerRefundedEvent.InputTuple,
      PlayerRefundedEvent.OutputTuple,
      PlayerRefundedEvent.OutputObject
    >;
    PlayerRefunded: TypedContractEvent<
      PlayerRefundedEvent.InputTuple,
      PlayerRefundedEvent.OutputTuple,
      PlayerRefundedEvent.OutputObject
    >;
  };
}
